import re
import sys

HLINE_FIELD = 9

# Right padding applied to select numeric fields
rpad = {1:r'\;', 3:r'\;\,', 6:r'\;\;', 8:r'\;\;'} 

def formatFields(fields, rpad):
    ''' Format the fields based upon the rules for this table '''
    fldstrings = []
    skipCount = 0
    for (i, f) in enumerate(fields):
        if skipCount > 0:
            # a \multicolumn to the left has coalesced this field
            skipCount -= 1
            continue
        f = f.strip()
        numMatch = re.match(r'(n/a)|(-?[0-9]+(\.[0-9]+)?)', f)
        if numMatch:
            if numMatch.group(1) == 'n/a':
                f = r'\mathrm{n/a}'
            # All numeric fields are in Math mode (for correct negative sign) and
            # fields with right-padding are right-padded
            fldstrings.append('$'+(f+rpad[i] if i in rpad else f)+'$')
        else: # Non-numeric field
            if f.startswith(r'\begin{tabular}'):
                # Eliminate padding on embedded tables
                fldstrings.append(r'{\setlength{\tabcolsep}{0pt}'+f+'}')
            else:
                multi = re.match(r'\\multicolumn\{(\d+)\}', f)
                if multi:
                    skipCount = int(multi.group(1))-1
                fldstrings.append(f)
    return '&'.join(fldstrings)

with open('apply-eqs.csv', 'r') as inp, open('apply-eqs.tex', 'w') as outp:
    outp.write('%%%%%% DO NOT MODIFY THIS FILE DIRECTLY %%%%%%\n')
    outp.write('%%%%%% IT IS GENERATED BY ' + sys.argv[0] + ' %%%%%%\n')
    for line in inp:
        fields = line.split('&')
        hf = fields[HLINE_FIELD].strip()
        if hf == r'\hline':
            if all([f == '' for f in fields[:HLINE_FIELD]]):
                outp.write(r'\\\hline' + '\n')
            else:
                outp.write(formatFields(fields[:HLINE_FIELD], rpad) + 
                           r' \\\hline' + '\n')
        else:
            outp.write(formatFields(fields[:HLINE_FIELD], rpad) + 
                       r' \\' + '\n')

    
